In [1]:
import torch

In [2]:
tensor = torch.rand(2, 3)
print(tensor)
print(tensor.dtype)

tensor([[0.9765, 0.2892, 0.7941],
        [0.9283, 0.2152, 0.5533]])
torch.float32


In [3]:
a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)

In [4]:
y = a+b
z = x * y

In [5]:
print(z)

tensor(20., grad_fn=<MulBackward0>)


In [6]:
print(z.grad_fn)
print(y.grad_fn)
print(a.grad_fn)
#For loss.backward walks the graph backwards

None


In [7]:
a = torch.tensor([[1,2], [3,4]])
b = torch.tensor([[10,20], [30,40]])

ewp = a * b
print(ewp)
print(a@b)

tensor([[ 10,  40],
        [ 90, 160]])
tensor([[ 70, 100],
        [150, 220]])


In [8]:
scores = torch.tensor([[10., 20., 30.], [15., 25., 40]]) #2 students
print(scores.mean())
print(scores.mean(dim=0)) #avg for each assignment
print(scores.mean(dim=1)) #avg for each student

tensor(23.3333)
tensor([12.5000, 22.5000, 35.0000])
tensor([20.0000, 26.6667])


In [9]:
n = 10
Din = 1
Dout = 1
X = torch.randn(n,Din)
w = torch.tensor([[2.0]])
b = torch.tensor([1.0])
yt = X @ w + b + torch.randn(n, Dout) * 0.1

In [10]:
fw = torch.randn(Din, Dout, requires_grad=True)
fb = torch.randn(1, requires_grad=True)

print(fw)
print(fb)

tensor([[-0.5147]], requires_grad=True)
tensor([0.6256], requires_grad=True)
