In [12]:
import torch
data = [[1, 2, 3], [4, 5, 6]]
t1 = torch.tensor(data)
print(t1)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [26]:
shape = (2,3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)
template = torch.tensor([[1, 2], [3, 4]])
randoml = torch.randn_like(template, dtype=torch.float32)
random2 = torch.randn(2,5)
print(ones, '\n', zeros, '\n', random, '\n', randoml, '\n', random2)
random2.dtype
random2.shape
random2.device

tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([[-0.9339, -0.8576,  0.0050],
        [ 0.6704, -0.5622, -0.2619]]) 
 tensor([[-0.3162,  2.2326],
        [ 1.7542, -1.4843]]) 
 tensor([[ 1.6976,  1.1909, -0.5581,  0.5408,  0.0104],
        [-1.3887, -0.7580, -1.0889,  0.9129,  0.5980]])


device(type='cpu')

In [27]:
x1 = torch.randn(shape, requires_grad=True)
x1.requires_grad

True

In [33]:

a = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)
x = torch.tensor(4.0, requires_grad=True)


y = a + b


z = x * y

print(y)
print(z)
print(x.grad_fn)
print(z.grad_fn)
#A graph connecting all is built behind the scenes

tensor(5., grad_fn=<AddBackward0>)
tensor(20., grad_fn=<MulBackward0>)
None


In [35]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[10, 20], [30, 40]])
ewproduct = a * b
print(ewproduct)
matrixproduct = a @ b
print(matrixproduct)

tensor([[ 10,  40],
        [ 90, 160]])
tensor([[ 70, 100],
        [150, 220]])


In [ ]:
scores = torch.tensor([[10., 20., 30.], [5., 10., 15.]])
print(scores.sum())
print(scores.mean())
print(scores.sum(dim=1)) #rows
print(scores.sum(dim=0)) #columns
print(scores.sum)

tensor(90.)
tensor(15.)
tensor([60., 30.])
tensor([15., 30., 45.])
<built-in method sum of Tensor object at 0x0000014122750E00>


In [57]:
x = torch.tensor([[0, 1, 2, 3],
                  [4, 5, 6, 7],
                  [8, 9, 10, 11]])
row2 = x[1]
print(row2)
row23 = x[1:]
print(row23)
ele1 = x[1,3]
print(ele1)

tensor([4, 5, 6, 7])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor(7)


In [59]:
mask = x>5
print(x[mask])
y = torch.where (x>4, -1, x)
print(y)

tensor([ 6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4, -1, -1, -1],
        [-1, -1, -1, -1]])


In [70]:
scores = torch.tensor([
    [10, 0, 5, 20, 1],  
    [1, 30, 2, 5, 0]   
])

best_indices = torch.argmax(scores, dim=1)
best_indices

tensor([3, 1])

In [73]:
indices_to_select = torch.tensor([[2], [0]])
selected_values = torch.gather(scores, dim=1, index=indices_to_select)
selected_values

tensor([[5],
        [1]])

In [75]:
# y - 2x + 1
N = 10
D_in = 1
D_out = 1

X = torch.randn(N, D_in)
true_W = torch.tensor([[2.0]])
true_b = torch.tensor(1.0)
y_true = X @ true_W + true_b + torch.randn(N, D_out) * 0.1 # Add a little noise

print(X[:])
print(y_true[:])

tensor([[-0.3848],
        [-0.2908],
        [-1.2533],
        [ 1.7720],
        [-0.6093],
        [-0.3203],
        [ 1.0194],
        [ 0.5686],
        [ 0.6975],
        [ 0.8413]])
tensor([[ 0.2801],
        [ 0.3781],
        [-1.5865],
        [ 4.6759],
        [-0.3792],
        [ 0.3996],
        [ 3.0174],
        [ 2.1358],
        [ 2.4574],
        [ 2.7310]])


In [76]:
W = torch.randn(D_in, D_out, requires_grad=True)
b = torch.randn(1, requires_grad=True)
print(W)
print(b)

tensor([[0.4587]], requires_grad=True)
tensor([-0.8642], requires_grad=True)


In [78]:
y_hat = X @ W + b
print(y_hat)
print(y_true)
error = y_hat - y_true
squared_error = error ** 2
loss = squared_error.mean()
print(loss)

tensor([[-1.0407],
        [-0.9976],
        [-1.4392],
        [-0.0513],
        [-1.1437],
        [-1.0111],
        [-0.3966],
        [-0.6034],
        [-0.5443],
        [-0.4783]], grad_fn=<AddBackward0>)
tensor([[ 0.2801],
        [ 0.3781],
        [-1.5865],
        [ 4.6759],
        [-0.3792],
        [ 0.3996],
        [ 3.0174],
        [ 2.1358],
        [ 2.4574],
        [ 2.7310]])
tensor(6.7048, grad_fn=<MeanBackward0>)


In [79]:
loss.backward()
print(W.grad)
print(b.grad)

tensor([[-3.3133]])
tensor([-4.3632])
